install:
  - choco install gitversion.portable -pre -y
  - choco install gitlink -y
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))

assembly_info:
  patch: false

configuration:
  - Release

platform:
  - Any CPU

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

after_build:
  - 7z a UIAVerify.zip %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\*.*
  
build_script:
  - cmd: msbuild visualuiaverify.sln "/p:Configuration=%CONFIGURATION%;Platform=%PLATFORM%"

cache:
  - packages -> **\packages.config
  
artifacts:
  - path: UIAVerify.zip
    name: Build
    
deploy:
  release: uiaverify-v$(appveyor_build_version)
  description: 'Latest'
  provider: GitHub
  auth_token:
    secure: cvVbVuSRxxOFGsfsso0t/Yqmuu8qSVKJMbC8WN8bJIN+mZ0r2mwSRd+xTiCtj/kx # your encrypted token from GitHub
  artifact: UIAVerify.zip
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only